name: giphy_client
description: A Giphy API Client for Dart compatible Web, Flutter, and server-side dart
version: 0.2.1
homepage: https://www.github.com/brianegan/giphy_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.2
  http: ^0.13.4

dev_dependencies:
  test: any
  mockito: any
  coverage: any
  pedantic: any
